version: "2"
services:
  client:
      image: mhart/alpine-node:slim-12.8.1
      restart: always
      ports:
        - "3000:3000"
      working_dir: /client/src/
      volumes:
        - ./client:/client/src/
      links:
        - api
      networks:
        - webappnetwork
  api:
    image: mhart/alpine-node:slim-12.8.1
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - webappnetwork
networks:
  webappnetwork:
      driver: bridge
